Repository asqw887/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#9 이슈 목록 화면 레이아웃 구현
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Assets.xcassets/UserImageIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/UserImageIcon.imageset/User Image Small (1).png
  IssueTracker/IssueTracker/Assets.xcassets/UserImageIcon.imageset/User Image Small.png
  IssueTracker/IssueTracker/Assets.xcassets/filterIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/filterIcon.imageset/Icon (1).png
  IssueTracker/IssueTracker/Assets.xcassets/filterIcon.imageset/Icon.png
  IssueTracker/IssueTracker/Assets.xcassets/issueIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/issueIcon.imageset/Property 1=alert-circle (2).png
  IssueTracker/IssueTracker/Assets.xcassets/milestoneIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/milestoneIcon.imageset/Vector (7).png
  IssueTracker/IssueTracker/Assets.xcassets/milestoneIcon.imageset/Vector (8).png
  IssueTracker/IssueTracker/Assets.xcassets/selectIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/selectIcon.imageset/Icon (2).png
  IssueTracker/IssueTracker/Assets.xcassets/selectIcon.imageset/Icon (3).png
  IssueTracker/IssueTracker/Assets.xcassets/tagIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/tagIcon.imageset/Vector (5).png
  IssueTracker/IssueTracker/Assets.xcassets/tagIcon.imageset/Vector (6).png
  IssueTracker/IssueTracker/IssueCell.swift
  IssueTracker/IssueTracker/IssueListViewController.swift
  IssueTracker/IssueTracker/SceneDelegate.swift
  IssueTracker/IssueTracker/TabBarViewController.swift
Labels: enhancement

#15 access_token 요청 후 이슈목록 화면으로 전환
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Info.plist
  IssueTracker/IssueTracker/Resource/API/Base/BaseTarget.swift
  IssueTracker/IssueTracker/Resource/API/Base/HTTPAcceptType.swift
  IssueTracker/IssueTracker/Resource/API/Base/HTTPContentType.swift
  IssueTracker/IssueTracker/Resource/API/Base/HTTPMethod.swift
  IssueTracker/IssueTracker/Resource/API/Base/NetworkError.swift
  IssueTracker/IssueTracker/Resource/API/DecodeManager.swift
  IssueTracker/IssueTracker/Resource/API/IssueTrackerTarget.swift
  IssueTracker/IssueTracker/Resource/API/LoginManager.swift
  IssueTracker/IssueTracker/Source/Support/SceneDelegate.swift
  IssueTracker/IssueTracker/Source/Support/ViewController.swift
Labels: enhancement

#17 sceneDelegate 경량화 & DecodeManager 분리
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Resource/API/DecodeManager.swift
  IssueTracker/IssueTracker/Resource/API/LoginManager.swift
  IssueTracker/IssueTracker/Resource/Repository/IssueTrackingRepository.swift
  IssueTracker/IssueTracker/Resource/Repository/LoginRepository.swift
  IssueTracker/IssueTracker/Resource/Repository/RequestRepository.swift
  IssueTracker/IssueTracker/Source/Support/SceneDelegate.swift
  IssueTracker/IssueTracker/Source/Support/ViewController.swift
  IssueTracker/MockIssueTest/MockIssueTest.swift
Labels: refactoring

#18 XCConfig 파일 설정 리뷰어 피드백 반영
  .gitignore
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/IssueTracker-Alpha.xcscheme
  IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/IssueTracker-Debug.xcscheme
  IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/IssueTracker-Release.xcscheme
  IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/IssueTracker.xcscheme
  IssueTracker/IssueTracker/Info.plist
  IssueTracker/IssueTracker/Resource/API/IssueTrackerTarget.swift
  IssueTracker/IssueTracker/Resource/API/LoginManager.swift
  IssueTracker/IssueTracker/Source/IssueList/View/IssueCell.swift
  IssueTracker/IssueTracker/Source/Support/Eevironment.swift
  IssueTracker/IssueTracker/Source/Support/LoginViewController.swift
  IssueTracker/IssueTracker/Source/Support/SceneDelegate.swift
Labels: enhancement

#21 IssueListViewModel 구현
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Resource/API/Base/BaseTarget.swift
  IssueTracker/IssueTracker/Resource/API/Base/HTTPHeader.swift
  IssueTracker/IssueTracker/Resource/API/Base/Provider.swift
  IssueTracker/IssueTracker/Resource/API/IssueTrackerTarget.swift
  IssueTracker/IssueTracker/Resource/Repository/IssueTrackingRepository.swift
  IssueTracker/IssueTracker/Source/IssueList/Model/State.swift
  IssueTracker/IssueTracker/Source/IssueList/View/IssueCell.swift
  IssueTracker/IssueTracker/Source/IssueList/View/IssueListViewController.swift
  IssueTracker/IssueTracker/Source/IssueList/ViewModel/IssueListViewModel.swift
  IssueTracker/IssueTracker/Source/Support/SceneDelegate.swift
Labels: enhancement

#22 Login vm#19 생성 및 관련 코드 refactoring
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Resource/API/Base/HTTPContentType.swift
  IssueTracker/IssueTracker/Resource/API/Base/Provider.swift
  IssueTracker/IssueTracker/Resource/API/DecodeManager.swift
  IssueTracker/IssueTracker/Resource/API/IssueTrackerTarget.swift
  IssueTracker/IssueTracker/Resource/Repository/LoginRepository.swift
  IssueTracker/IssueTracker/Source/Login/LoginViewController.swift
  IssueTracker/IssueTracker/Source/Login/LoginViewModel.swift
  IssueTracker/IssueTracker/Source/Support/SceneDelegate.swift
  IssueTracker/MockIssueTest/MockIssueTest.swift
Labels: enhancement, refactoring

#23 Feedback hotfix 2주차 수요일 피드백 일부 반영
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Resource/API/Base/HTTPAcceptType.swift
  IssueTracker/IssueTracker/Resource/API/Base/HTTPAuthorization.swift
  IssueTracker/IssueTracker/Resource/API/Base/HTTPContentType.swift
  IssueTracker/IssueTracker/Resource/API/Base/NetworkError.swift
  IssueTracker/IssueTracker/Resource/API/Base/Provider.swift
  IssueTracker/IssueTracker/Resource/Repository/IssueTrackingRepository.swift
  IssueTracker/IssueTracker/Resource/Repository/LoginRepository.swift
  IssueTracker/IssueTracker/Source/IssueList/Model/Issue.swift
  IssueTracker/IssueTracker/Source/IssueList/Model/State.swift
  IssueTracker/IssueTracker/Source/IssueList/ViewModel/IssueListViewModel.swift
  IssueTracker/IssueTracker/Source/Support/SceneDelegate.swift
  IssueTracker/MockIssueTest/MockIssueTest.swift
Labels: bug, refactoring

#24 첫화면 보여주는 흐름의 로직을 정리
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Resource/API/Base/HTTPHeader.swift
  IssueTracker/IssueTracker/Resource/API/Base/NetworkError.swift
  IssueTracker/IssueTracker/Resource/API/Base/Provider.swift
  IssueTracker/IssueTracker/Resource/API/IssueTrackerTarget.swift
  IssueTracker/IssueTracker/Resource/Repository/IssueTrackingRepository.swift
  IssueTracker/IssueTracker/Resource/Repository/LoginRepository.swift
  IssueTracker/IssueTracker/Source/IssueList/View/IssueListViewController.swift
  IssueTracker/IssueTracker/Source/IssueList/ViewModel/IssueListViewModel.swift
  IssueTracker/IssueTracker/Source/Login/LoginViewModel.swift
  IssueTracker/IssueTracker/Source/Support/RootWindow.swift
  IssueTracker/IssueTracker/Source/Support/RootWindowViewModel.swift
  IssueTracker/IssueTracker/Source/Support/SceneDelegate.swift
Labels: bug, enhancement

#30 [#29] fix: CollectionView 로 구성되어 있는 작업을 TableView로 전환
  IssueTracker/IssueTracker/Source/Present/IssueList/View/IssueCell.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/View/IssueListViewController.swift
  IssueTracker/IssueTracker/Source/Present/Window/View/RootWindow.swift
Labels: refactoring
